openapi: "3.0.0"
info:
  version: 1.0.0
  title: dailyApi
  description: Daily API
paths:
  /daily:
    get:
      description: dailyを複数取得
      operationId: findDaily
      parameters:
        - name: asc
          in: query
          description: 昇順にするかどうか
          required: false
          schema:
            type: boolean
        - name: limit
          in: query
          description: 取得する件数
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: daily response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Daily"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: dailyの新規作成
      operationId: addDaily
      requestBody:
        description: 追加するdaily
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewDaily"
      responses:
        "200":
          description: daily response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Daily"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /daily/{id}:
    get:
      description: dataをidを指定して取得
      operationId: findDailyById
      parameters:
        - name: id
          in: path
          description: 取得したいデータのid
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: daily response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Daily"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Daily:
      allOf:
        - $ref: "#/components/schemas/NewDaily"
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
    NewDaily:
      type: object
      required:
        - email
        - date
        - tasks
      properties:
        email:
          type: string
          format: email
        date:
          type: string
        tasks:
          type: array
          items:
            type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string